### ISSUE TITLE
Very awesome!But I can't install

### ISSUE THREAD

**Issue by sinoon** [actionless/awesome_config#13]
Very awesome config , I was deep impressive.

I fellow the guild in README , when I finished and restart awesome occur error
```
Oops, there were errors during startup!
error while running function
stac traceback:
    ...noon/.config/awesoome/third_party/revelation/init.lua:340 in function 'init'
    /home/sinoon/.config/awesome/config/keys.lua:21 in main chunk
    [C]: in function 'require'
    /home/sinoon/.config/awesome/config/init.lua:8: in main chunk
    [C]: in function 'require'
    /home/sinoon/.config/awesome/rc.lua:70: in main chunk
error: ...noon/.config/awesome/third_party/revelation/init.lua:340 attempt to concatenate field 'fg_normal' (a nil value)
```

Should I found a theme that theme.lua have the 'fg_normal'?

**Comment by sinoon** [comment]
My awesome version
```
awesome v3.5.6 (For Those About To Rock)
 • Build: Jan 14 2015 20:56:29 for x86_64 by gcc version 4.8.2 (buildd@lgw01-04)
 • Compiled against Lua 5.1.5 (running with Lua 5.1)
 • D-Bus support: ✔
```

**Comment by actionless** [comment]
Thanks!
I am using awesome from git master but that problem seems unrelated.

Can you please attach `xrdb -query` output? I guess you don't have terminal colorscheme set in ~/.Xresources (i will add fallback values to the theme now)

**Comment by actionless** [comment]
https://github.com/actionless/awesome_config/commit/4500642f641afddeb07c34042176e771822d186a

**Comment by sinoon** [comment]
Very thoughtful , Thank you.

`xrdb -query` output:
```
*customization:	-color
Xft.antialias:	1
Xft.dpi:	96
Xft.hinting:	1
Xft.hintstyle:	hintslight
Xft.rgba:	rgb
```

When I restart awesome , no long show this error.

I'm sorry I have less knowledge about `awesome`.

But now I got a anther error:
```
Oops, an error happened!
/home/sinoon/.config/awesome/actionless/helpers.lua:38: attempt to call field 'timer' (a nil value)
```
```
Oops, there were errors during startup!
error while running function
stack tracceback:
     /home/sinoon/.config/awesome/actionless/helpgers.lua:38: in function 'newinterval'
    ...sinoon/.config/awesome/actionless/widgets/netctl.lua:105: in function <...sinoon/.config/awesome/actionless/widgets/netctl.lua:18>
    (tail call):?
    /home/sinoon/.config/awesome/config/widgets.lua:33: in function 'init'
    /home/sinoon/.config/awesome/rc.lua:76: in main chunk
error:/home/sinoon/.config/awesome/actionless/helpers.lua:38: attempt to call field 'timer'(a nil value)
```
it's seem like call a function that no exist. I don't how it happened.

so , I open `helpers.lua` and find line 38 
```
local timer = gears.timer({ timeout = timeout })
```
But in my computer /usr/share/awesome/lib/gears , `timer.lua` doesn't exist , only have:
`color.lua`,`debug.lua`,`init.lua`,`object.lua`,`sort.lua`,`surface.lua`,`wallpaper.lua`

Is my awesome version wrong? or because my awesome install by PPA?

**Comment by actionless** [comment]
that's because i am using awesome from git master, i put a workaround for that now:
https://github.com/actionless/awesome_config/commit/de72768bbe851d1aa1c87bead4a238673efa2683

**Comment by sinoon** [comment]
I'm so sorry about it ...

Another error
```
Oops, an error happened!
...e/sinoon/.config/awesome/actionless/widgets/temp.lua:34: attempt to compare number with nil
```
```
Oops, an error happened!
...me/sinoon/.config/awesome/actionless/widgets/bat,lua:42: bad argument #2 to 'format' (string expected,got nil)
```

Yesterday,I restart `awesome` success with error by remove some widgets,but,then that is ugly...

I'm so sorry taken too much you time , maybe I can't use you config , default config is good enough for me.I give up..

With all of my respect , thank you ~!

**Comment by actionless** [comment]
about temp and bat:
either `upower` and `lm-sensors` (i guess i should add that to the readme) are not installed, either widget target is not exists (ie sensor name or battery name)

i think it would be easier to contact each other via jabber or IRC
