### ISSUE TITLE
Hi actionless, Love your awesome theme, I would love the spotify music

### ISSUE THREAD

**Issue by tjw0lf** [actionless/awesome_config#19]
Hi actionless Love your Awesome WM theme awesome work really would like your spotify and music scripts from awesome if you can help me on how to do this. I already have an awesome WM desktop if you can help me on what to do Thanks, oh yeah what version of awesome WM you on

**Comment by tjw0lf** [comment]
I saw your screenshot on unixporn, with spotify notify in corner music i like that's what i meant, I use spotfiy all the time and clemintine https://www.reddit.com/r/unixporn/comments/5wk9pe/awesome_wm_no_oomox_this_time/

**Comment by SethBarberee** [comment]
I think this might be of some use:
https://github.com/actionless/awesome_config/blob/devel/actionless/widgets/music/widget.lua

He detects which player and chages the icon

**Comment by tjw0lf** [comment]
OK Thanks how would i put music folder in rc.lua or whatever

**Comment by actionless** [comment]
@tjw0lf you need to put whole directories `actionless` and `utils` to your `~/.config/awesome`

and add to rc.lua:

```lua
    -- Add widgets to the wibox
    s.mywibox:setup {
        layout = wibox.layout.align.horizontal,
        { -- Left widgets
            layout = wibox.layout.fixed.horizontal,
            mylauncher,
            s.mytaglist,
            s.mypromptbox,
        },
        s.mytasklist, -- Middle widget
        { -- Right widgets
            layout = wibox.layout.fixed.horizontal,
----------------------------
            require("actionless.widgets.music.widget")({
              backends = {'spotify', 'clementine'},
              bg="#888a85",
              fg="#0e0021",
              pause_fg="#ff0000",
              pause_bg="#000000",
            }),
----------------------------
            mykeyboardlayout,
            wibox.widget.systray(),
            mytextclock,
            s.mylayoutbox,
        },
    }

```

**Comment by tjw0lf** [comment]
What awesome WM version are you using?

And where in the rc.lua do I add it. And how like so.

Can you show me how it supposed to be like in the rc.lua. Thank you for replying great work

**Comment by actionless** [comment]
version 4.2, it was an example with default rc.lua, go here for more info:
https://awesomewm.org/doc/api/documentation/07-my-first-awesome.md.html

**Comment by tjw0lf** [comment]
Why did you close this actiionkess? Not solved

No I'm sayiing where do I put it in the rc.lua please show me.

**Comment by actionless** [comment]
that's not issue, you're just trolling me
