### ISSUE TITLE
Help with your music folder awesome WM

### ISSUE THREAD

**Issue by batmanm0b1E** [actionless/awesome_config#22]
I'm currently running awesome wm 4.2 and would love to add your music spotify and stuff. And i had look at your rc.lua wanted to know how i add them to mine if you can be helpful. thanks in advance

**Comment by batmanm0b1E** [comment]
OK i got your awesome config working but need help Windows sizing for 1080p mointor how do i drag corners down can help?

**Comment by actionless** [comment]
events for window borders/titlebars are defined here:
https://github.com/actionless/awesome_config/blob/devel/actionless/titlebar.lua#L20-L38

**Comment by batmanm0b1E** [comment]
OK thank you been most helpful
