### ISSUE TITLE
remove screenshot of the old hotkey popup

### ISSUE THREAD

**Issue by frioux** [actionless/awesome_config#26]
Hi!  I *love* the keyboard oriented hotkey popup you have screenshots of, but I can't figure out where the code is for it.  Do you mind linking to it?  Thanks!

**Comment by actionless** [comment]
that screenshot is outdated, that widget has changed a lot and finally merged to awesomewm upstream but without some questionable functionality

although you can find the code of that old version here in git history:

https://github.com/actionless/awesome_config/blob/b85577ba57d283adf563119c33349421c00fc2f3/actionless/hotkey_resources.lua

but basically as you see it have hardcoded US keyboard layout and other stuff is not so smart as well

**Comment by frioux** [comment]
Gotcha; so there's no keyboard oriented hotkeys in core, right?

**Comment by actionless** [comment]
no, only what you have when press mod+s


btw reopening it in order to not forget to update readme
