### ISSUE TITLE
Complains about not having ruled

### ISSUE THREAD

**Issue by mrtnpwn** [actionless/awesome_config#27]
I was trying to use this config but then awesome complained about not finding a module called `ruled`

**Comment by actionless** [comment]
please make sure you followed all the instructions correctly:
https://github.com/actionless/awesome_config/blob/master/README.md#installation

**Comment by mrtnpwn** [comment]
I literally did everything from it, it's not really useful that you just linked me to the README.md + closed the issue

**Comment by mrtnpwn** [comment]
Got it working, technically, but suddenly when I restarted my awesome it sends me straight to the login menu (I'm using Linux Mint) and I can't start it

**Comment by actionless** [comment]
what AwesomeWM version and which branch of the config do you have?

**Comment by mrtnpwn** [comment]
I'm using AwesomeWM 4.2 and, since the `master` branch complains about ruled, I tried `awesome43` and it worked, but it just crashes

**Comment by actionless** [comment]
and what's written on first two lines by the link i've pasted here?
