### ISSUE TITLE
:question: is it possible to get systray icons be disblayed at the top-bar?

### ISSUE THREAD

**Issue by iharh** [actionless/awesome_config#28]
Is it possible to get systray icons be displayed at the top-bar vs side-bar, just like in a screenshot:
* https://raw.githubusercontent.com/actionless/awesome_config/master/screenshots/screenshot_new.png

**Comment by actionless** [comment]
only by moving systray inside config/toolbar_horizontal.lua

**Comment by iharh** [comment]
I'm trying to put the following into config/keys.lua:
`
  local panel_widget_separator = wibox.container.background(
    common.constraint({ width=beautiful.panel_widget_spacing, }),
    beautiful.panel_widget_bg
  )
  awesome_context.widgets.systray_toggle = common.panel_widget_shape(widgets.sneaky_toggle({
      widgets={
        panel_widget_separator,
      --  w.netctl,
      --  panel_widget_separator,
      },
      enable_sneaky_tray = true,
      --margin = {right = beautiful.panel_padding_bottom},
      panel_widget_shape = false,
  }))
`
but get exception:
`
2021-09-14 16:55:36 E: awesome: Error during a protected call: ...e/iharh/.config/awesome/actionless/widgets/lcarslist.lua:176: attempt to call a table value (field 'icon_sizes')
stack traceback:
	...e/iharh/.config/awesome/actionless/widgets/lcarslist.lua:176: in function <...e/iharh/.config/awesome/actionless/widgets/lcarslist.lua:73>
	(...tail calls...)
	/usr/local/share/awesome/lib/awful/widget/common.lua:147: in function 'awful.widget.common.list_update'
	...e/iharh/.config/awesome/actionless/widgets/lcarslist.lua:189: in upvalue 'tag_group'
	...e/iharh/.config/awesome/actionless/widgets/lcarslist.lua:215: in upvalue 'tasklist_update'
	...e/iharh/.config/awesome/actionless/widgets/lcarslist.lua:261: in function <...e/iharh/.config/awesome/actionless/widgets/lcarslist.lua:260>
	[C]: in function 'xpcall'
	/usr/local/share/awesome/lib/gears/protected_call.lua:36: in function </usr/local/share/awesome/lib/gears/protected_call.lua:35>
	(...tail calls...)
	/usr/local/share/awesome/lib/gears/timer.lua:255: in function 'gears.timer.run_delayed_calls_now'
`

**Comment by actionless** [comment]
are you using LCARS mode? otherwise such stacktrace shouldn't appear at all (see hotkeys list popup to how disable lcars mode if you don't need it)

**Comment by iharh** [comment]
No, I'm just copy&paste from lcars code.

**Comment by actionless** [comment]
should be fixed by 253c3ab4f21b7683f9ad00db33e05ffc2c24c62c and 982874c23663c2142749413212321a30edcef153

**Comment by iharh** [comment]
Thank you, but I still have troubles. At config/keys.lua at keys.init I'm using:
`
  local panel_widget_separator = wibox.container.background(
    common.constraint({ width=beautiful.panel_widget_spacing, }),
    beautiful.panel_widget_bg
  )
  awesome_context.widgets.systray_toggle =
      widgets.sneaky_toggle({
        widgets={
          panel_widget_separator,
        --  w.netctl,
        --  panel_widget_separator,
        },
        enable_sneaky_tray = true,
        --margin = {right = beautiful.panel_padding_bottom},
        panel_widget_shape = false,
      })
`
But still can't see my systrace widget. I've added nlog(...) traces through the sneaky_togle and sneaky_tray show methods. All stuff is called, but I don't see anything on screen

**Comment by actionless** [comment]
mb you trying to add more than one tray

**Comment by iharh** [comment]
Let me share my changes:
* https://gist.github.com/24a4cebc9cb79d6603b78302c822f2c1

**Comment by actionless** [comment]
i dont have time to go through it all but quick search by word `systray` shown me what you added one more systray but didn't removed the existing one (inside notifications sidebar) - you can't have two x11 trays at the same time

**Comment by iharh** [comment]
I've just removed systray_toggle from config/lcars_toolbar_horizontal.lua, but still can't see my own systray.

**Comment by actionless** [comment]
![2021-09-15--1631708849_217x28_scrot](https://user-images.githubusercontent.com/1655669/133433230-f57cf7bd-c527-4737-96a5-775bf034e603.png)

**Comment by iharh** [comment]
I've just managed to put systray there, but without toggle functionality. Polishing ...
