### ISSUE TITLE
gtk theme

### ISSUE THREAD

**Issue by LuchianMihai** [actionless/awesome_config#29]
Hi, 
I've traced your pull request on main awesome repo about making awesome look like a current GTK+ 3 theme.
I've got an issue, awesome colors ends up being the default ones. It passes gears_debug.print_warning("Can't load GTK+3 theme. Using 'xresources' theme as a fallback.") without throwing an warning though.
Is there something I am missing? Thanks and sorry for bothering.
P.S. actually, I've made it work once which baffles my mind why (for adapta gtk theme), guess I am setting gtk theme wrong?

**Comment by actionless** [comment]
you mistakenly reported it here instead of awesome bugtracker
